{{/*
This template serves as a blueprint for Service Account objects that are created
using the common library.
*/}}
{{- define "common.serviceaccount" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
imagePullSecrets:
{{- range $_, $VALUE := .Values.serviceAccount.imagePullSecrets }}
- name: {{ $VALUE.name }}
{{- end }}
{{- end -}}
{{- end -}}
