{{/*
This template serves as the blueprint for the Secret objects that are created
within the common library used by envFrom on Deployment.
*/}}
{{- define "common.shared.env-secret" -}}
{{- if .Values.global.sharedEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: env-secret-shared
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $KEY, $VALUE := .Values.global.sharedEnvSecret }}
  {{ $KEY }}: {{ $VALUE | b64enc }}
{{- end }}
{{- end -}}
{{- end -}}
