apiVersion: v2
appVersion: 0.0.1
description: Gitlab Helm Chart Library
home: https://github.com/lpmatos/helm-library
icon: https://cdn.icon-icons.com/icons2/2248/PNG/512/tools_icon_137091.png
keywords:
  - common
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: lpsm-dev@protonmail.com
    name: CI Monk
name: common
sources:
  - https://github.com/lpmatos/helm-library
type: library
version: 0.0.1
