{{/*
This template serves as the blueprint for the Secret objects
that are created within the common library.
*/}}
{{- define "common.loop.env-secret" -}}
{{ $releaseNamespace := .Release.Namespace }}
{{ $labels := include "common.labels" . }}
{{- if .Values.applications }}
{{- range .Values.applications }}
---
{{ $project := .gitlab.project | replace "/" "-" }}
{{- if .extraEnvSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: env-secret-{{ $project }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
data:
{{- range $KEY, $VALUE := .extraEnvSecret }}
  {{ $KEY }}: {{ $VALUE | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
